name: spark401-marquez

services:
  postgres:
    image: postgres:13
    container_name: marquez-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    volumes:
      - marquez_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marquez -d marquez -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - spark401-spark 

  marquez:
    image: marquezproject/marquez:latest
    container_name: marquez-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MARQUEZ_CONFIG: /opt/marquez/marquez.yml
    volumes:
      - ./marquez.yml:/opt/marquez/marquez.yml:ro
    ports:
      - "5001:5000"   # host 5001 -> container app 5000
      - "5002:5001"   # host 5002 -> container admin 5001 (nếu admin port là 5001)
    networks:
      - spark401-spark 

  marquez-ui:
    image: marquezproject/marquez-web:latest
    container_name: marquez-ui
    restart: unless-stopped
    depends_on:
      - marquez
    environment:
      WEB_PORT: "3000"
      MARQUEZ_HOST: marquez
      MARQUEZ_PORT: "5000"
    ports:
      - "3000:3000"
    networks:
      - spark401-spark 

volumes:
  marquez_pgdata:

networks:
  spark401-spark:
    external: true
    name: spark401-spark

