- conn_id: spark_default
  conn_type: spark
  host: spark-master
  port: 7077
  extra: '{"spark_home": "/opt/spark", "spark_submit_bin": "/opt/spark/bin/spark-submit"}'

- conn_id: google_cloud_default
  conn_type: google_cloud_platform
  extra: '{"extra__google_cloud_platform__project": "my-cdp-demo-01"}'
