services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9002"
    ports:
      - "9000:9000"   # S3 API
      - "9002:9002"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ../../data/minio:/data
    networks:
      - spark401-spark 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 12

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -lc "
      set -e;
      mc alias set local http://minio:9000 minioadmin minioadmin123;

      # Create bucket (only ONE bucket)
      mc mb -p local/lakehouse || true;

      # Create prefixes by uploading a keep file (S3 has no real folders)
      echo 'keep' | mc pipe local/lakehouse/bronze/.keep;
      echo 'keep' | mc pipe local/lakehouse/silver/.keep;
      echo 'keep' | mc pipe local/lakehouse/gold/.keep;
      echo 'keep' | mc pipe local/lakehouse/checkpoints/.keep;

      mc ls local/lakehouse;
      "
    networks:
      - spark401-spark 

networks:
  spark401-spark:
    external: true
    name: spark401-spark